db:
  image: mysql:5.6
  container_name: orocrm_mysql
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=orocrm
    - MYSQL_USER=orocrm
    - MYSQL_PASSWORD=orocrm
  volumes:
    - orocrm_data:/var/lib/mysql
orocrm:
  image: magestore/orocrm
  container_name: orocrm
  links:
    - "db"
  expose:
    ["80", "8080", "443", "465", "587", "993", "995"]
  ports:
    - "80:80"
    - "8080:8080"
    - "443:443"
    - "465:465"
    - "587:587"
    - "993:993"
    - "995:995"
  #command: ["bash", "-c", "while true; do sleep 1; done;"]
  entrypoint: /run.sh
